symfony/src/Entity/Artist.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Sonata\SonataMediaMedia;
use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArtistRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE', region: 'member')]
class Artist implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 190)]
    private string $name = '';

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $genre = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $type = null;

    #[Assert\Expression(
        '!(!value or !this.getBioEn())',
        message: 'artist.form.error',
    ),]
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $bio = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $hardware = null;

    /**
     * @var Collection<int, EventArtistInfo>
     */
    #[ORM\OneToMany(
        targetEntity: EventArtistInfo::class,
        mappedBy: 'Artist',
        cascade: ['persist', 'detach'],
    ),]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    private Collection $eventArtistInfos;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $updatedAt;

    #[ORM\ManyToOne(targetEntity: Member::class, inversedBy: 'artist')]
    private ?Member $member = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $bioEn = null;

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $links = [];

    #[ORM\ManyToOne(
        targetEntity: SonataMediaMedia::class,
        cascade: ['persist', 'detach'],
    ),]
    private ?SonataMediaMedia $Picture = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $copyForArchive = false;

    public function __construct()
    {
        $this->eventArtistInfos = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $now = new \DateTimeImmutable();
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getHardware(): ?string
    {
        return $this->hardware;
    }

    public function setHardware(?string $hardware): self
    {
        $this->hardware = $hardware;

        return $this;
    }

    /**
     * @return Collection<int, EventArtistInfo>
     */
    public function getEventArtistInfos(): Collection
    {
        return $this->eventArtistInfos;
    }

    public function addEventArtistInfo(EventArtistInfo $eventArtistInfo): self
    {
        if (!$this->eventArtistInfos->contains($eventArtistInfo)) {
            $this->eventArtistInfos[] = $eventArtistInfo;
            $eventArtistInfo->setArtist($this);
        }

        return $this;
    }

    public function removeEventArtistInfo(
        EventArtistInfo $eventArtistInfo,
    ): self {
        if ($this->eventArtistInfos->contains($eventArtistInfo)) {
            $this->eventArtistInfos->removeElement($eventArtistInfo);
            // set the owning side to null (unless already changed)
            if ($eventArtistInfo->getArtist() === $this) {
                $eventArtistInfo->setArtist(null);
            }
        }

        return $this;
    }

    public function clearEventArtistInfos(): void
    {
        $this->eventArtistInfos->clear();
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    #[\Override]
    public function __toString(): string
    {
        return $this->name;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;
        if ($member instanceof Member) {
            $member->addArtist($this);
        }

        return $this;
    }

    public function getBioEn(): ?string
    {
        return $this->bioEn;
    }

    /**
     * Return the bio in the preferred language.
     * If locale is 'fi', prefer Finnish bio ($bio) then fallback to English.
     * For any other locale, prefer English bio ($bioEn) then fallback to Finnish.
     */
    public function getBioByLocale(?string $locale): ?string
    {
        if ('fi' === $locale) {
            return $this->bio ?? $this->bioEn;
        }

        return $this->bioEn ?? $this->bio;
    }

    public function setBioEn(?string $bioEn): self
    {
        $this->bioEn = $bioEn;

        return $this;
    }

    public function getLinks(): ?array
    {
        return $this->links;
    }

    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    public function getPicture(): ?SonataMediaMedia
    {
        return $this->Picture;
    }

    public function setPicture(?SonataMediaMedia $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getCopyForArchive(): ?bool
    {
        return $this->copyForArchive;
    }

    public function setCopyForArchive(?bool $copyForArchive): self
    {
        $this->copyForArchive = $copyForArchive;

        return $this;
    }

    public function getLinkUrls(): ?string
    {
        $ret = '';
        foreach ($this->links as $link) {
            $ret .= '<a href="'.$link['url'].'">'.$link['title'].'</a>';
            if (end($this->links) !== $link) {
                $ret .= ' | ';
            }
        }

        return $ret;
    }
}

symfony/src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Rental\Booking\Reward;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE', region: 'member')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, \Stringable, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Length(min: 8)]
    private string $password = '';

    #[Assert\Length(min: 8)]
    private ?string $plainPassword = null;

    #[ORM\OneToOne(
        targetEntity: Member::class,
        inversedBy: 'user',
        cascade: ['persist', 'remove'],
    ),]
    #[ORM\JoinColumn(unique: true, nullable: false, onDelete: 'CASCADE')]
    private Member $member;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $CreatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $UpdatedAt;

    /**
     * @var Collection<int, Reward>
     */
    #[ORM\OneToMany(
        targetEntity: Reward::class,
        mappedBy: 'user',
        orphanRemoval: true,
    ),]
    private Collection $rewards;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $LastLogin = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $MattermostId = null;

    /**
     * @var Collection<int, AccessGroups>
     */
    #[ORM\ManyToMany(targetEntity: AccessGroups::class, mappedBy: 'users')]
    private Collection $accessGroups;

    #[ORM\Column(length: 255)]
    private string $authId = '';

    public function __construct()
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
        $this->rewards = new ArrayCollection();
        $this->accessGroups = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->member->getEmail();
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        if ($this->member->getUsername()) {
            return $this->member->getUsername();
        }

        return 'N/A';
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    #[\Override]
    public function getUserIdentifier(): string
    {
        if ($this->member->getEmail()) {
            return $this->member->getEmail();
        }

        return 'N/A';
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        foreach ($this->accessGroups as $group) {
            if ($group->getActive()) {
                foreach ($group->getRoles() as $role) {
                    $roles[] = $role;
                }
            }
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getMember(): Member
    {
        return $this->member;
    }

    public function setMember(Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->LastLogin;
    }

    public function setLastLogin(?\DateTimeImmutable $LastLogin): self
    {
        $this->LastLogin = $LastLogin;

        return $this;
    }

    /**
     * @return Collection<int, Reward>
     */
    public function getRewards(): Collection
    {
        return $this->rewards;
    }

    public function addReward(Reward $reward): self
    {
        if (!$this->rewards->contains($reward)) {
            $this->rewards[] = $reward;
            $reward->setUser($this);
        }

        return $this;
    }

    public function removeReward(Reward $reward): self
    {
        if ($this->rewards->contains($reward)) {
            $this->rewards->removeElement($reward);
        }

        return $this;
    }

    public function getMattermostId(): ?string
    {
        return $this->MattermostId;
    }

    public function setMattermostId(?string $MattermostId): self
    {
        $this->MattermostId = $MattermostId;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
        $this->password = '';
    }

    /**
     * @return Collection<int, AccessGroups>
     */
    public function getAccessGroups(): Collection
    {
        return $this->accessGroups;
    }

    public function addAccessGroup(AccessGroups $accessGroup): self
    {
        if (!$this->accessGroups->contains($accessGroup)) {
            $this->accessGroups[] = $accessGroup;
            $accessGroup->addUser($this);
        }

        return $this;
    }

    public function removeAccessGroup(AccessGroups $accessGroup): self
    {
        if ($this->accessGroups->removeElement($accessGroup)) {
            $accessGroup->removeUser($this);
        }

        return $this;
    }

    #[\Override]
    public function __toString(): string
    {
        return (string) $this->member->getName();
    }

    public function getLocale(): string
    {
        return $this->member->getLocale();
    }

    public function getAuthId(): string
    {
        return $this->authId;
    }

    public function setAuthId(string $authId): static
    {
        $this->authId = $authId;

        return $this;
    }
}

symfony/templates/announcements.html.twig
{% extends 'onecolumn.html.twig' %}
{% use 'pieces/event.html.twig' %}
{% block title %}{{ 'page.announcements.title'|trans }} | Entropy ry{% endblock %}
{% block content %}
    {% set newyear = date('Y') %}
    {% set route = 'entropy_event' %}

    <h1>{{ 'page.announcements.title'|trans }}</h1>

    <div id="announcements">
        {% for event in events %}
            {% if app.user %}
                {% set visible = true %}
            {% else %}
                {% set visible = app.user is null and event.published %}
            {% endif %}
            {% set year = event.eventdate|date('Y') %}
            {% if event is not null and visible %}
                {% if loop.first %}
                    <div class="row">
                        <div id="event-content" class="col overflow-auto">
                            {{ block('event_head') }}
                            {{ block('event_content') }}
                        </div>
                        {% if event.picture is not null and event.picturePosition == 'after' %}
                            <div class="img-after mb-2 mt-3">{{ block('event_media') }}</div>
                        {% endif %}
                    </div>
                {% else %}
                    {% if loop.index == 2 %}
                        <hr>
                    {% endif %}
                    {% if year != newyear %}
                        <div class="linetext">
                            <span>{{ year }}</span>
                        </div>
                    {% endif %}
                    <div class="post"
                         data-type="{{ event.type }}"
                         data-cancelled="{{ event.cancelled }}">{{ block('events') }}</div>
                {% endif %}
            {% endif %}
            {% set newyear = event.eventdate|date('Y') %}
        {% endfor %}
    </div>
{% endblock %}
{% block events %}
    <h5 class="d-flex justify-content-between">
        <span {% if event.cancelled %}style="text-decoration: line-through;"{% endif %}>
            {% if event.url is empty and event.externalUrl %}
                {{ event.nameByLang(app.request.locale) }}
            {% else %}
                {% if event.url and not event.externalUrl %}
                    <a href="{{ path('entropy_event_slug', {slug: event.url, year: event.eventdate|date('Y')}) }}">
                {% else %}
                    <a href="{{ path(route, {id: event.id}) }}">
                {% endif %}
                    {{ event.nameByLang(app.request.locale) }}
                    </a>
            {% endif %}
        </span>
        <span class="border-bottom flex-fill">
            {% if event.epics %}
                <a style="position: relative;
                            float: right;
                            right: 30%"
                    href="{{ event.epics }}"><twig:ux:icon name="image" /></a>
            {% endif %}
        </span>
        <span>
            {{ event.publishdate|date('j.n.') }}
        </span>
    </h5>
{% endblock %}

symfony/templates/contract.html.twig
{% extends 'onecolumn.html.twig' %}
{% block title %}{{ bookingdata.name }} - {{ bookingdata.date }}{% endblock %}
{% block content %}
    <div class="col-md-12">
    <input type="button"
            value="Print"
            class="no-print btn btn-primary float-end"
            onClick="window.print()">
    {% if renter %}
        {% set loc = 'content' ~ ((app.request.locale)|capitalize) %}
        {{ attribute(contract, loc)|markdown_to_html }}
    {% endif %}
    <h1>{{ bookingdata.name }} - {{ bookingdata.date }}</h1>
    {% if bookingdata.packages %}
        <h3 style="text-transform: capitalize;">{{ 'packages'|trans }}</h3>
        {% for package in bookingdata.packages %}
            <div>
                <input type="checkbox">
                <label>{{ package }}:</label>
                {% if package.rent %}<span class="float-end package-rent-price">{{ package.rent }} €</span>{% endif %}
            </div>
            <ul class="list-unstyled">
                {% set show_price = false %}
                {% for item in package.items %}<li>{{ block('item') }}</li>{% endfor %}
            </ul>
        {% endfor %}
    {% endif %}
    {% if bookingdata.items %}
        <h3 style="text-transform: capitalize;">{{ 'items'|trans }}</h3>
        {% set show_price = true %}
        {% for item in bookingdata.items %}{{ block('item') }}{% endfor %}
    {% endif %}
    {% if bookingdata.accessories %}
        <h3 style="text-transform: capitalize;" class="mt-3">
            {{ 'accessories'|trans }}
            {% if bookingdata.rent.accessories %}
                <span class="float-end fs-6 fw-normal">{{ bookingdata.rent.accessories }}€</span>
            {% endif %}
        </h3>
        <p>({{ 'contract.accessories.prices'|trans }})</p>
        <ul class="list-unstyled">
            {% for item in bookingdata.accessories %}
                <li>
                    <input type="checkbox">
                    <label>
                        <span class="lead">{{ item.count }}</span> X {{ item.name }}
                    </label>
                    {% if item.compensationPrice %}
                        <span class="float-end">{{ item.compensationPrice }} €/{{ 'pcs'|trans }}</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if renter %}
        <hr>
        <h3 style="text-transform: capitalize;">{{ 'renter'|trans }}</h3>
        {{ renter.name }}
        <br>
        {% if renter.organization %}
            {{ renter.organization }}
            <br>
        {% endif %}
        {% if renter.phone %}
            {{ renter.phone }}
            <br>
        {% endif %}
        {{ renter.email }}
        <hr>
        <div class="text-center">
            {{ 'Total rent price'|trans }}: <span>{{ bookingdata.actualTotal }}€</span>
        </div>
        <hr>
        <h3>Allekirjoitus</h3>
        <p class="text-muted small">
            {{ 'contract.signature_note'|trans }}
        </p>
        <div {{ stimulus_controller('signature') }}>
            <div style="height: 260px">
                {% if bookingdata.renterSignature is empty %}
                    <canvas data-signature-target="canvas"
                            {% if app.user.member.theme|default('light') == 'dark' %}class="invert"{% endif %}
                            style="touch-action: none;
                                    user-select: none"
                            width="800"
                            height="260"></canvas>
                {% endif %}
                <div id="signature"
                        data-signature-target="signature"
                        {% if app.user.member.theme|default('light') == 'dark' %}class="invert"{% endif %}>
                    {% if bookingdata.renterSignature is not empty %}
                        <img class="img-fluid" src="{{ bookingdata.renterSignature }}">
                    {% endif %}
                </div>
            </div>
            <div class="consent_form">
                {% if bookingdata.renterSignature is empty %}
                    <button style="display: none"
                            data-signature-target="clearBtn"
                            data-action="signature#clearCanvas"
                            class="btn btn-secondary">Poista ja tee uusi allekirjoitus</button>
                    <button data-action="signature#saveCanvas"
                            data-signature-target="saveBtn"
                            class="btn btn-primary">Tallenna allekirjoitus</button>
                {% endif %}
            </div>
            <hr>
            {{ form_start(form) }}
                {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
        <input type="button"
                value="Print"
                class="no-print btn btn-primary float-end"
                onClick="window.print()">
    </div>
    {% endif %}
{% endblock %}
{%- block item %}
    <div class="form-check">
        <input type="checkbox" class="me-2">
        <label>{{ item }}</label>
        <small>
            {% if item.Manufacturer %}, Manufacturer: {{ item.Manufacturer }}{% endif %}
            {% if item.model %}, Model: {{ item.model }}{% endif %}
            {% if item.serialNumber %}, S/N: {{ item.serialNumber }}{% endif %}
        </small>
        {% for file in item.files %}<span class="no-print">- {{ file.downloadLink|raw }}</span>{% endfor %}
        {% if show_price %}<span class="float-end item-rent-price">{{ item.rent }} €</span>{% endif %}
    </div>
{% endblock -%}

symfony/templates/contract_public.html.twig
{% extends 'onecolumn.html.twig' %}
{% block title %}
    {% if label_key %}
        {{ label_key|trans }}
    {% else %}
        {{ contract.purpose }}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="col-md-12 contract-public">
        <div class="contract-content">
            {% set loc = 'content' ~ ((app.request.locale)|capitalize) %}
            {{ attribute(contract, loc)|markdown_to_html }}
        </div>
    </div>
{% endblock %}

symfony/templates/list_nakki_info_for_responsible.html.twig
{% extends 'event.html.twig' %}
{% block content %}
    {% if is_granted('ROLE_SUPER_ADMIN') %}<h1 class="text-success">You are ADMIN</h1>{% endif %}
    {{ block('responsibles') }}
    {{ block('infos') }}
{% endblock %}
{% block responsibles %}
    {% if responsibles|length > 0 and infos|length > 0 %}
        {% set theme = event.theme == 'dynamic' ? (app.user ? app.user.member.theme : null) : event.theme %}
        <h3>{{ 'Responsibles'|trans }}</h3>
        <table class="table table-striped {% if theme == 'dark' %}table-dark{% endif %} ">
            <thead>
                <tr>
                    <th scope="col">Nakki</th>
                    <th scope="col">{{ 'Responsible'|trans }}</th>
                    <th scope="col">Channel</th>
                </tr>
            </thead>
            <tbody>
                {% for name, nakki in responsibles %}
                    {% if nakki.responsible %}
                        {% set r = nakki.responsible %}
                    {% else %}
                        {% set r = 'missing' %}
                    {% endif %}
                    <tr>
                        <th scope="col">{{ name }}</th>
                        <th scope="col">
                            {% if r == 'missing' %}
                                {{ r|trans }}
                            {% else %}
                                {{ r.username }}, {{ r.name }}, {{ r.phone }}, {{ r.email }}
                            {% endif %}
                        </th>
                        <th scope="col">
                            <a class="btn btn-success" target="_blank" href="{{ nakki.mattermost }}">
                                <twig:ux:icon name="link-out" /> Mattermost
                            </a>
                        </th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}
{% block infos %}
{% set theme = event.theme == 'dynamic' ? (app.user ? app.user.member.theme : null) : event.theme %}
    {% for name, nakki in infos %}
        <h3>
            Nakki: {{ name }}
            {% if nakki.mattermost is not empty %}
                <a class="btn btn-secondary float-end"
                   target="_blank"
                   href="{{ nakki.mattermost }}">
                    <twig:ux:icon name="link-out" /> Mattermost
                </a>
            {% endif %}
        </h3>
        {% if nakki.responsible is not null %}
            {# {% set r = nakki.responsible %} #}
            {# <table class="table table-striped #} {# {% if event.headerTheme == 'dark' %} #} {# table-dark #} {# {% endif %} #} {# "> #}
            {# <thead> #}
            {# <tr> #}
            {# <th scope="col">{{ 'Username'|trans }}</th> #}
            {# <th scope="col">{{ 'Name'|trans }}</th> #}
            {# <th scope="col">{{ 'Phone'|trans }}</th> #}
            {# <th scope="col">Email</th> #}
            {# </tr> #}
            {# </thead> #}
            {# <tbody> #}
            {# <tr> #}
            {# <th scope="col">{{ r.username }}</th> #}
            {# <th scope="col">{{ r.name }}</th> #}
            {# <th scope="col">{{ r.phone }}</th> #}
            {# <th scope="col">{{ r.email }}</th> #}
            {# </tr> #}
            {# </tbody> #}
            {# </table> #}
        {% else %}
            <h5 class="text-warning">{{ 'Responsible'|trans }}: {{ 'missing'|trans }}</h5>
        {% endif %}
        {{ block('thead') }}
        {% for bookings in nakki.b %}
            {% for b in bookings %}
                {% if b.member is not null %}
                    <tr>
                        <th>{{ b.member.username }}</th>
                        <td>{{ b.member.name }}</td>
                        {% if not gdpr|default(false) %}
                            <td>{{ b.member.phone }}</td>
                            <td>{{ b.member.email }}</td>
                        {% endif %}
                        {% if event.nakkikone and event.nakkikone.requiresDifferentTimes %}
                            <td>
                                {{ b.startAt|date }}
                            </th>
                        {% endif %}
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% else %}
<h1>{{ 'No permissions'|trans }}</h1>
{% endfor %}
{% endblock %}
{% block thead %}
        <table class="table table-striped {% if theme == 'dark' %}table-dark{% endif %} ">
        <thead>
            <tr>
                <th scope="col">{{ 'Username'|trans }}</th>
                <th scope="col">{{ 'Name'|trans }}</th>
                {% if not gdpr|default(false) %}
                    <th scope="col">{{ 'Phone'|trans }}</th>
                    <th scope="col">Email</th>
                {% endif %}
                {% if event.nakkikone and event.nakkikone.requiresDifferentTimes %}<th scope="col">Time</th>{% endif %}
            </tr>
        </thead>
        <tbody>
        {% endblock %}