symfony/src/Entity/Nakki.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\NakkiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: NakkiRepository::class)]
class Nakki implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: NakkiDefinition::class)]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private NakkiDefinition $definition;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $startAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $endAt;

    /**
     * @var Collection<int, NakkiBooking>
     */
    #[ORM\OneToMany(targetEntity: NakkiBooking::class, mappedBy: 'nakki', orphanRemoval: true)]
    private Collection $nakkiBookings;

    #[ORM\ManyToOne(targetEntity: Nakkikone::class, inversedBy: 'nakkis')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotBlank]
    private Nakkikone $nakkikone;

    #[ORM\Column(type: 'dateinterval')]
    private \DateInterval $nakkiInterval;

    #[ORM\ManyToOne(targetEntity: Member::class, inversedBy: 'responsibleForNakkis')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?Member $responsible = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $mattermostChannel = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableBookings = null;

    public function __construct()
    {
        $this->nakkiBookings = new ArrayCollection();
        $this->nakkiInterval = new \DateInterval('PT1H');
    }

    #[\Override]
    public function __toString(): string
    {
        return '' !== (string) $this->definition && '0' !== (string) $this->definition ? $this->definition->getNameEn() : 'N/A';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDefinition(): NakkiDefinition
    {
        return $this->definition;
    }

    public function setDefinition(NakkiDefinition $definition): self
    {
        $this->definition = $definition;

        return $this;
    }

    public function getStartAt(): \DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): \DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    /**
     * @return Collection|NakkiBooking[]
     */
    public function getNakkiBookings(): Collection
    {
        return $this->nakkiBookings;
    }

    public function addNakkiBooking(NakkiBooking $nakkiBooking): self
    {
        if (!$this->nakkiBookings->contains($nakkiBooking)) {
            $this->nakkiBookings[] = $nakkiBooking;
            $nakkiBooking->setNakki($this);
        }

        return $this;
    }

    public function removeNakkiBooking(NakkiBooking $nakkiBooking): self
    {
        $this->nakkiBookings->removeElement($nakkiBooking);

        return $this;
    }

    public function getEvent(): Event
    {
        return $this->nakkikone->getEvent();
    }

    public function getNakkikone(): Nakkikone
    {
        return $this->nakkikone;
    }

    public function setNakkikone(Nakkikone $nakkikone): self
    {
        $this->nakkikone = $nakkikone;

        return $this;
    }

    public function getNakkiInterval(): ?\DateInterval
    {
        return $this->nakkiInterval;
    }

    public function setNakkiInterval(\DateInterval $nakkiInterval): self
    {
        $this->nakkiInterval = $nakkiInterval;

        return $this;
    }

    public function getTimes(): array
    {
        $times = [];
        $diff = $this->getStartAt()->diff($this->getEndAt());
        $hours = $diff->h;
        $hours = ($hours + ($diff->days * 24)) / ((int) $this->getNakkiInterval()->format('%h'));
        for ($i = 0; $i < $hours; ++$i) {
            $start = $i * (int) $this->getNakkiInterval()->format('%h');
            $times[] = $this->getStartAt()->modify($start.' hour');
        }

        return $times;
    }

    public function getMemberByTime($date): ?Member
    {
        foreach ($this->getNakkiBookings() as $booking) {
            if ($booking->getStartAt() == $date && $booking->getMember()) {
                return $booking->getMember();
            }
        }

        return null;
    }

    public function getResponsible(): ?Member
    {
        return $this->responsible;
    }

    public function setResponsible(?Member $responsible): self
    {
        $this->responsible = $responsible;

        return $this;
    }

    public function getMattermostChannel(): ?string
    {
        return $this->mattermostChannel;
    }

    public function setMattermostChannel(?string $mattermostChannel): self
    {
        $this->mattermostChannel = $mattermostChannel;

        return $this;
    }

    public function isDisableBookings(): ?bool
    {
        return $this->disableBookings;
    }

    public function setDisableBookings(?bool $disableBookings): static
    {
        $this->disableBookings = $disableBookings;

        return $this;
    }
}

symfony/src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Rental\Booking\Reward;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE', region: 'member')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, \Stringable, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Length(min: 8)]
    private string $password = '';

    #[Assert\Length(min: 8)]
    private ?string $plainPassword = null;

    #[ORM\OneToOne(
        targetEntity: Member::class,
        inversedBy: 'user',
        cascade: ['persist', 'remove'],
    ),]
    #[ORM\JoinColumn(unique: true, nullable: false, onDelete: 'CASCADE')]
    private Member $member;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $CreatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $UpdatedAt;

    /**
     * @var Collection<int, Reward>
     */
    #[ORM\OneToMany(
        targetEntity: Reward::class,
        mappedBy: 'user',
        orphanRemoval: true,
    ),]
    private Collection $rewards;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $LastLogin = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $MattermostId = null;

    /**
     * @var Collection<int, AccessGroups>
     */
    #[ORM\ManyToMany(targetEntity: AccessGroups::class, mappedBy: 'users')]
    private Collection $accessGroups;

    #[ORM\Column(length: 255)]
    private string $authId = '';

    public function __construct()
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
        $this->rewards = new ArrayCollection();
        $this->accessGroups = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->member->getEmail();
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        if ($this->member->getUsername()) {
            return $this->member->getUsername();
        }

        return 'N/A';
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    #[\Override]
    public function getUserIdentifier(): string
    {
        if ($this->member->getEmail()) {
            return $this->member->getEmail();
        }

        return 'N/A';
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        foreach ($this->accessGroups as $group) {
            if ($group->getActive()) {
                foreach ($group->getRoles() as $role) {
                    $roles[] = $role;
                }
            }
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getMember(): Member
    {
        return $this->member;
    }

    public function setMember(Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->LastLogin;
    }

    public function setLastLogin(?\DateTimeImmutable $LastLogin): self
    {
        $this->LastLogin = $LastLogin;

        return $this;
    }

    /**
     * @return Collection<int, Reward>
     */
    public function getRewards(): Collection
    {
        return $this->rewards;
    }

    public function addReward(Reward $reward): self
    {
        if (!$this->rewards->contains($reward)) {
            $this->rewards[] = $reward;
            $reward->setUser($this);
        }

        return $this;
    }

    public function removeReward(Reward $reward): self
    {
        if ($this->rewards->contains($reward)) {
            $this->rewards->removeElement($reward);
        }

        return $this;
    }

    public function getMattermostId(): ?string
    {
        return $this->MattermostId;
    }

    public function setMattermostId(?string $MattermostId): self
    {
        $this->MattermostId = $MattermostId;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
        $this->password = '';
    }

    /**
     * @return Collection<int, AccessGroups>
     */
    public function getAccessGroups(): Collection
    {
        return $this->accessGroups;
    }

    public function addAccessGroup(AccessGroups $accessGroup): self
    {
        if (!$this->accessGroups->contains($accessGroup)) {
            $this->accessGroups[] = $accessGroup;
            $accessGroup->addUser($this);
        }

        return $this;
    }

    public function removeAccessGroup(AccessGroups $accessGroup): self
    {
        if ($this->accessGroups->removeElement($accessGroup)) {
            $accessGroup->removeUser($this);
        }

        return $this;
    }

    #[\Override]
    public function __toString(): string
    {
        return (string) $this->member->getName();
    }

    public function getLocale(): string
    {
        return $this->member->getLocale();
    }

    public function getAuthId(): string
    {
        return $this->authId;
    }

    public function setAuthId(string $authId): static
    {
        $this->authId = $authId;

        return $this;
    }
}

symfony/templates/components/Profile/Compensations.html.twig
<div class="box">
    <div class="box-header">
        <h5 class="box-title">{{ 'profile.paid_renting_rewards'|trans }}</h5>
    </div>
    <div class="box-body">
        {% for reward in app.user.rewards|reverse|slice(0, 5) %}
            {% if reward.PaidDate %}
                {{ reward.PaidDate|date('d.m.Y') }}: {{ reward.Evenout }}€
                <br>
            {% else %}
                {{ 'profile.next_reward_is_bubbling_under'|trans }}
                <br>
            {% endif %}
        {% else %}
            {{ 'profile.no_renting_rewards'|trans }}
        {% endfor %}
    </div>
</div>

symfony/templates/components/Profile/MemberInfo.html.twig
<div class="box">
    <div class="box-header">
        <h5 class="box-title">{{ 'membership_information'|trans }}</h5>
    </div>
    <div class="box-body">
        <ul class="fa-ul">
            <li>
                <span class="fa-li"><twig:ux:icon name="user" /></span>
                {{ member.name }}, {{ member.username }}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="image" /></span>
                <span>{{ 'member.epics_username'|trans }}:</span>
                {% if member.epicsUsername %}
                    {{ member.epicsUsername }}
                {% else %}
                    <em>{{ 'member.epics_username.not_set'|trans }}</em>
                {% endif %}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="envelope" /></span>
                {% if not member.emailVerified %}
                    <p class="text-danger">{{ member.email }} - {{ 'member.email_unverified'|trans }}</p>
                    <a href="{{ path('profile_resend_verification') }}" class="btn btn-primary btn-sm" data-turbo="false">{{ 'resend_verification'|trans }}</a>
                {% else %}
                    {{ member.email }}
                {% endif %}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="lock" /></span>
                ********
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="phone" /></span>
                {{ member.phone }}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="city" /></span>
                {{ member.CityOfResidence }}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="language" /></span>
                {{ member.locale|trans }}&nbsp;
            </li>
            <li>
                <span class="fa-li">
                    {% if member.StudentUnionMember %}
                        <twig:ux:icon name="check-square" />
                    {% else %}
                        <twig:ux:icon name="square" />
                    {% endif %}
                </span>
                {{ 'Student union member'|trans }}
            </li>
            <li>
                <span class="fa-li"><twig:ux:icon name="palette" /></span>
                {{ member.theme|default('bright')|trans }}&nbsp;
            </li>
            <li>
                <span class="fa-li">
                    {% if member.allowInfoMails %}
                        <twig:ux:icon name="check-square" />
                    {% else %}
                        <twig:ux:icon name="square" />
                    {% endif %}
                </span>
                {{ 'member.allow_info_mails'|trans }}
            </li>
            {% if member.allowActiveMemberMails %}
            <li>
                <span class="fa-li">
                    {% if member.allowActiveMemberMails %}
                        <twig:ux:icon name="check-square" />
                    {% else %}
                        <twig:ux:icon name="square" />
                    {% endif %}
                </span>
                {{ 'member.allow_active_member_mails'|trans }}
            </li>
            {% endif %}
        </ul>
        <div class="d-grid gap-2">
            <a class="btn btn-primary btn-large" href="{{ path('profile_edit') }}">{{ 'edit'|trans|capitalize }}</a>
            <a class="btn btn-primary" href="{{ path('entropy_event_calendar_config') }}">{{ 'calendar.heading'|trans }}</a>
        </div>
    </div>
</div>

symfony/templates/components/Profile/MemberSituation.html.twig
{% set member = app.user.member %}
<div class="box">
    <div class="box-header">
        <h5 class="box-title">{{ 'membership_status'|trans }}</h5>
    </div>
    <div class="box-body">
        <ul class="fa-ul">
            <li>
                <span class="fa-li"><twig:ux:icon name="star" /></span>
                <div class="progress" style="height: 25px;">
                    <div class="progress-bar progress-bar-striped progress-bar-animated"
                            role="progressbar"
                            style="width: {{ member.ProgressP }}%"
                            aria-valuenow="{{ member.ProgressP }}"
                            aria-valuemin="0"
                            aria-valuemax="100">
                        {% if member.acceptedAsHonoraryMember %}
                            {{ 'HC member'|trans }}
                        {% elseif member.isActiveMember %}
                            {{ 'Active member'|trans }}
                        {% else %}
                            {{ 'Member'|trans }}
                        {% endif %}
                    </div>
                </div>
            </li>
        </ul>
        <div class="row offset-1 pb-2">
            <div class="col-md-4">
                {% if member %}
                    <twig:ux:icon name="check-square" height="1.2em" />
                {% else %}
                    <twig:ux:icon name="square" height="1.2em"/>
                {% endif %}
                {{ 'Member account created'|trans }}:
                {{ member.createdAt|date('d.m.Y') }}
            </div>
            <div class="col-md-4">
                <span>
                    {% if member.isActiveMember %}
                        <twig:ux:icon name="check-square" height="1.2em"/>
                    {% else %}
                        <twig:ux:icon name="square" height="1.2em"/>
                    {% endif %}
                    {{ 'Active member'|trans }}
                    {% if member.ApplicationHandledDate %}{{ 'since'|trans }} {{ member.ApplicationHandledDate|date('d.m.Y') }}{% endif %}
                    {% if not member.isActiveMember %}
                        <a class="btn btn-primary btn-sm"
                            href="{{ path('apply_for_active_member') }}">{{ 'profile.apply_for_active_member'|trans|capitalize }}</a>
                    {% endif %}
                </span>
            </div>
            <div class="col-md-4">
                <span>
                    {% if member.AcceptedAsHonoraryMember %}
                        <twig:ux:icon name="check-square" height="1.2em"/>
                    {% else %}
                        <twig:ux:icon name="square" height="1.2em"/>
                    {% endif %}
                    {{ 'HC member'|trans }}
                    {% if member.AcceptedAsHonoraryMember %}
                        {{ 'since'|trans }} {{ member.AcceptedAsHonoraryMember|date('d.m.Y') }}
                    {% endif %}
                </span>
            </div>
            <div class="col-md-11 justify-content-end">
                {% if member.canVote %}
                    <twig:ux:icon name="check-square" height="1.2em"/>
                {% else %}
                    <twig:ux:icon name="square" height="1.2em"/>
                {% endif %}
                {{ 'member.can_vote'|trans }}
            </div>
        </div>
        <hr>
        <ul class="fa-ul">
            <li>
                <span class="fa-li"><twig:ux:icon name="users-gear" /></span>
                {{ 'profile.access_groups'|trans }}:
                {% for group in member.user.AccessGroups %}
                    {% if group.active %}
                        {{ this.group }}
                        {% if not loop.last %},{% endif %}
                    {% endif %}
                {% else %}
                    {{ 'profile.no_access_groups'|trans }}
                {% endfor %}
            </li>
        </ul>
    </div>
</div>

symfony/templates/components/Profile/Tickets.html.twig
{% if this.tickets|length > 0 %}
    <div class="box">
        <div class="box-header">
            <h5>{{ 'block.tickets.name'|trans }}</h5>
        </div>
        <div class="box-body">
            <div class="row">
                {% for ticket in this.tickets %}
                    {% if ticket.referenceNumber %}
                        <div class="col-10 mx-auto mb-2 d-flex gap-2">
                            <a href="{{ path('entropy_event_ticket', {year: ticket.event.eventDate|date('Y'), slug: ticket.event.url, reference: ticket.referenceNumber}) }}"
                                class="btn btn-primary flex-grow-1">{{ ticket.event.name(app.request.locale) }}</a>
                            {% if ticket.checkout and ticket.checkout.receiptUrl %}
                                <a href="{{ ticket.checkout.receiptUrl }}"
                                    class="btn btn-outline-secondary"
                                    target="_blank"
                                    rel="noopener">{{ 'ticket.receipt'|trans }}</a>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}