symfony/src/Entity/Nakki.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\NakkiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: NakkiRepository::class)]
class Nakki implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: NakkiDefinition::class)]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private NakkiDefinition $definition;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $startAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $endAt;

    /**
     * @var Collection<int, NakkiBooking>
     */
    #[ORM\OneToMany(targetEntity: NakkiBooking::class, mappedBy: 'nakki', orphanRemoval: true)]
    private Collection $nakkiBookings;

    #[ORM\ManyToOne(targetEntity: Nakkikone::class, inversedBy: 'nakkis')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotBlank]
    private Nakkikone $nakkikone;

    #[ORM\Column(type: 'dateinterval')]
    private \DateInterval $nakkiInterval;

    #[ORM\ManyToOne(targetEntity: Member::class, inversedBy: 'responsibleForNakkis')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?Member $responsible = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $mattermostChannel = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableBookings = null;

    public function __construct()
    {
        $this->nakkiBookings = new ArrayCollection();
        $this->nakkiInterval = new \DateInterval('PT1H');
    }

    #[\Override]
    public function __toString(): string
    {
        return '' !== (string) $this->definition && '0' !== (string) $this->definition ? $this->definition->getNameEn() : 'N/A';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDefinition(): NakkiDefinition
    {
        return $this->definition;
    }

    public function setDefinition(NakkiDefinition $definition): self
    {
        $this->definition = $definition;

        return $this;
    }

    public function getStartAt(): \DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): self
    {
        $this->startAt = $startAt;

        return $this;
    }

    public function getEndAt(): \DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    /**
     * @return Collection|NakkiBooking[]
     */
    public function getNakkiBookings(): Collection
    {
        return $this->nakkiBookings;
    }

    public function addNakkiBooking(NakkiBooking $nakkiBooking): self
    {
        if (!$this->nakkiBookings->contains($nakkiBooking)) {
            $this->nakkiBookings[] = $nakkiBooking;
            $nakkiBooking->setNakki($this);
        }

        return $this;
    }

    public function removeNakkiBooking(NakkiBooking $nakkiBooking): self
    {
        $this->nakkiBookings->removeElement($nakkiBooking);

        return $this;
    }

    public function getEvent(): Event
    {
        return $this->nakkikone->getEvent();
    }

    public function getNakkikone(): Nakkikone
    {
        return $this->nakkikone;
    }

    public function setNakkikone(Nakkikone $nakkikone): self
    {
        $this->nakkikone = $nakkikone;

        return $this;
    }

    public function getNakkiInterval(): ?\DateInterval
    {
        return $this->nakkiInterval;
    }

    public function setNakkiInterval(\DateInterval $nakkiInterval): self
    {
        $this->nakkiInterval = $nakkiInterval;

        return $this;
    }

    public function getTimes(): array
    {
        $times = [];
        $diff = $this->getStartAt()->diff($this->getEndAt());
        $hours = $diff->h;
        $hours = ($hours + ($diff->days * 24)) / ((int) $this->getNakkiInterval()->format('%h'));
        for ($i = 0; $i < $hours; ++$i) {
            $start = $i * (int) $this->getNakkiInterval()->format('%h');
            $times[] = $this->getStartAt()->modify($start.' hour');
        }

        return $times;
    }

    public function getMemberByTime($date): ?Member
    {
        foreach ($this->getNakkiBookings() as $booking) {
            if ($booking->getStartAt() == $date && $booking->getMember()) {
                return $booking->getMember();
            }
        }

        return null;
    }

    public function getResponsible(): ?Member
    {
        return $this->responsible;
    }

    public function setResponsible(?Member $responsible): self
    {
        $this->responsible = $responsible;

        return $this;
    }

    public function getMattermostChannel(): ?string
    {
        return $this->mattermostChannel;
    }

    public function setMattermostChannel(?string $mattermostChannel): self
    {
        $this->mattermostChannel = $mattermostChannel;

        return $this;
    }

    public function isDisableBookings(): ?bool
    {
        return $this->disableBookings;
    }

    public function setDisableBookings(?bool $disableBookings): static
    {
        $this->disableBookings = $disableBookings;

        return $this;
    }
}

symfony/src/Entity/RSVP.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\RSVPRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RSVPRepository::class)]
#[ORM\HasLifecycleCallbacks]
class RSVP implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Event::class, inversedBy: 'RSVPs')]
    #[ORM\JoinColumn(nullable: false)]
    private Event $event;

    #[ORM\ManyToOne(targetEntity: Member::class, inversedBy: 'RSVPs')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Member $member = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::STRING, length: 255, unique: true, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEvent(): Event
    {
        return $this->event;
    }

    public function setEvent(Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getName(): ?string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAvailableLastName(): string
    {
        if ($this->getMember() instanceof Member) {
            return ucfirst((string) $this->getMember()->getLastname());
        }

        return ucfirst((string) $this->lastName);
    }

    public function getAvailableEmail(): string
    {
        if ($this->getMember() instanceof Member) {
            return $this->getMember()->getEmail();
        }

        return $this->email;
    }

    #[\Override]
    public function __toString(): string
    {
        return 'ID: '.$this->id;
    }
}

symfony/src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Rental\Booking\Reward;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE', region: 'member')]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, \Stringable, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\Length(min: 8)]
    private string $password = '';

    #[Assert\Length(min: 8)]
    private ?string $plainPassword = null;

    #[ORM\OneToOne(
        targetEntity: Member::class,
        inversedBy: 'user',
        cascade: ['persist', 'remove'],
    ),]
    #[ORM\JoinColumn(unique: true, nullable: false, onDelete: 'CASCADE')]
    private Member $member;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $CreatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private \DateTimeImmutable $UpdatedAt;

    /**
     * @var Collection<int, Reward>
     */
    #[ORM\OneToMany(
        targetEntity: Reward::class,
        mappedBy: 'user',
        orphanRemoval: true,
    ),]
    private Collection $rewards;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $LastLogin = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $MattermostId = null;

    /**
     * @var Collection<int, AccessGroups>
     */
    #[ORM\ManyToMany(targetEntity: AccessGroups::class, mappedBy: 'users')]
    private Collection $accessGroups;

    #[ORM\Column(length: 255)]
    private string $authId = '';

    public function __construct()
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
        $this->rewards = new ArrayCollection();
        $this->accessGroups = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $now = new \DateTimeImmutable();
        $this->CreatedAt = $now;
        $this->UpdatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->UpdatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->member->getEmail();
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        if ($this->member->getUsername()) {
            return $this->member->getUsername();
        }

        return 'N/A';
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    #[\Override]
    public function getUserIdentifier(): string
    {
        if ($this->member->getEmail()) {
            return $this->member->getEmail();
        }

        return 'N/A';
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        foreach ($this->accessGroups as $group) {
            if ($group->getActive()) {
                foreach ($group->getRoles() as $role) {
                    $roles[] = $role;
                }
            }
        }

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    #[\Override]
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getMember(): Member
    {
        return $this->member;
    }

    public function setMember(Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): self
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->LastLogin;
    }

    public function setLastLogin(?\DateTimeImmutable $LastLogin): self
    {
        $this->LastLogin = $LastLogin;

        return $this;
    }

    /**
     * @return Collection<int, Reward>
     */
    public function getRewards(): Collection
    {
        return $this->rewards;
    }

    public function addReward(Reward $reward): self
    {
        if (!$this->rewards->contains($reward)) {
            $this->rewards[] = $reward;
            $reward->setUser($this);
        }

        return $this;
    }

    public function removeReward(Reward $reward): self
    {
        if ($this->rewards->contains($reward)) {
            $this->rewards->removeElement($reward);
        }

        return $this;
    }

    public function getMattermostId(): ?string
    {
        return $this->MattermostId;
    }

    public function setMattermostId(?string $MattermostId): self
    {
        $this->MattermostId = $MattermostId;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
        $this->password = '';
    }

    /**
     * @return Collection<int, AccessGroups>
     */
    public function getAccessGroups(): Collection
    {
        return $this->accessGroups;
    }

    public function addAccessGroup(AccessGroups $accessGroup): self
    {
        if (!$this->accessGroups->contains($accessGroup)) {
            $this->accessGroups[] = $accessGroup;
            $accessGroup->addUser($this);
        }

        return $this;
    }

    public function removeAccessGroup(AccessGroups $accessGroup): self
    {
        if ($this->accessGroups->removeElement($accessGroup)) {
            $accessGroup->removeUser($this);
        }

        return $this;
    }

    #[\Override]
    public function __toString(): string
    {
        return (string) $this->member->getName();
    }

    public function getLocale(): string
    {
        return $this->member->getLocale();
    }

    public function getAuthId(): string
    {
        return $this->authId;
    }

    public function setAuthId(string $authId): static
    {
        $this->authId = $authId;

        return $this;
    }
}

symfony/templates/components/Nakki/Board.html.twig
{% set attrs = attributes.defaults({
    class: 'nakki-board',
    'data-controller': 'scroll-planner',
}) %}
<div{{ attrs }}>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            {% if event.url and not event.externalUrl %}
                {% set eventPath = path('entropy_event_slug.' ~ app.request.locale, {slug: event.url, year: event.eventDate|date('Y')}) %}
            {% else %}
                {% set eventPath = path('entropy_event.' ~ app.request.locale, {id: event.id}) %}
            {% endif %}
            <h1 class="h3 mb-1">
                <a href="{{ eventPath }}">{{ event.nameByLang(app.request.locale) }}</a>
            </h1>
            <small class="text-muted">{{ event.eventDate|date('d.m.Y H:i') }}</small>
        </div>
        <div class="btn-group" role="group">
            <a href="{{ path('entropy_event_slug_nakkikone', {year: event.eventDate.format('Y'), slug: event.url}) }}"
               class="btn btn-sm btn-outline-primary"
               target="_blank"
               title="{{ 'nakkikone.admin.view_public_page'|trans }}">
                {{ ux_icon('nakki-users', {class: 'icon-sm'}) }}
                <span class="d-none d-lg-inline ms-1">{{ 'nakkikone.admin.public_short'|trans }}</span>
            </a>
            <button type="button"
                    class="btn btn-sm {{ this.scheduleOnly ? 'btn-primary' : 'btn-outline-primary' }}"
                    data-action="live#action"
                    data-live-action-param="toggleSchedule"
                    title="{{ 'nakkikone.board.schedule_title'|trans }}">
                {{ ux_icon('nakki-calendar', {class: 'icon-sm'}) }}
                <span class="d-none d-lg-inline ms-1">{{ 'nakkikone.board.schedule_title'|trans }}</span>
            </button>
            <a href="{{ path('entropy_event_responsible', {year: event.eventDate.format('Y'), slug: event.url}) }}"
               class="btn btn-sm btn-outline-info"
               target="_blank"
               title="{{ 'nakkikone.admin.responsible_page'|trans }}">
                {{ ux_icon('nakki-id', {class: 'icon-sm'}) }}
                <span class="d-none d-lg-inline ms-1">{{ 'nakkikone.admin.responsible_short'|trans }}</span>
            </a>
            <a href="{{ path('admin_app_event_nakkiList', {id: event.id}) }}"
               class="btn btn-sm btn-outline-secondary"
               target="_blank"
               title="{{ 'nakkikone.admin.printable_list'|trans }}">
                {{ ux_icon('nakki-print', {class: 'icon-sm'}) }}
                <span class="d-none d-lg-inline ms-1">{{ 'nakkikone.admin.print_short'|trans }}</span>
            </a>
            <a href="{{ path('admin_app_event_edit', {id: event.id}) }}"
               class="btn btn-sm btn-outline-secondary"
               title="{{ 'nakkikone.admin.event_settings'|trans }}">
                {{ ux_icon('nakki-settings', {class: 'icon-sm'}) }}
                <span class="d-none d-lg-inline ms-1">{{ 'nakkikone.admin.settings_short'|trans }}</span>
            </a>
        </div>
    </div>

    {% if this.scheduleOnly %}
        <div class="card shadow-sm border-0" id="nakkikone-schedule">
            <div class="card-header bg-dark text-white">
                <h2 class="h5 mb-0">{{ 'nakkikone.board.schedule_title'|trans }}</h2>
            </div>
            <div class="card-body">
                {% set grid = this.scheduleGrid %}
                {% if grid.timeSlots is empty %}
                    <div class="alert alert-info mb-0">{{ 'nakkikone.board.schedule_no_bookings'|trans }}</div>
                {% else %}
                    <div class="table-responsive">
                        <table class="table table-bordered table-sm table-striped nakkikone-schedule-table">
                            <thead>
                                <tr>
                                    <th class="nakkikone-schedule-time">{{ 'nakkikone.board.schedule_time'|trans }}</th>
                                    {% for i in 1..grid.maxColumns %}
                                        <th class="nakkikone-schedule-slot">{{ 'nakkikone.board.schedule_slot'|trans }} {{ i }}</th>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for slot in grid.timeSlots %}
                                    {% set rowIndex = loop.index0 %}
                                    <tr>
                                        <td class="fw-semibold align-middle nakkikone-schedule-time">
                                            {{ slot.time|date('H:i') }}
                                        </td>

                                        {% set columnMap = {} %}
                                        {% for bookingData in slot.bookings %}
                                            {% set columnMap = columnMap|merge({(bookingData.column): bookingData}) %}
                                        {% endfor %}

                                        {% for col in 0..(grid.maxColumns - 1) %}
                                            {% if columnMap[col] is defined %}
                                                {% set bookingData = columnMap[col] %}
                                                {% if bookingData.booking is not null %}
                                                    {% set booking = bookingData.booking %}
                                                <td rowspan="{{ bookingData.rowspan }}"
                                                    class="{{ booking.member ? 'table-success text-dark' : '' }} align-middle border-end nakkikone-schedule-cell">
                                                    <div class="fw-semibold">
                                                        {{ booking.nakki.definition.getName(app.request.locale) }}
                                                    </div>
                                                    {% if booking.member %}
                                                        <span class="badge bg-success mb-1">{{ 'nakkikone.column.reserved'|trans }}</span><br>
                                                        <strong>{{ booking.member.name }}</strong>
                                                        {% if booking.member.email %}
                                                            <br><small>{{ booking.member.email }}</small>
                                                        {% endif %}
                                                    {% else %}
                                                        <span class="badge bg-secondary">{{ 'nakkikone.column.available'|trans }}</span>
                                                    {% endif %}
                                                        <br>
                                                        {% if not booking.member %}
                                                            <small class="text-muted">
                                                                {{ booking.startAt|date('H:i') }}–{{ booking.endAt|date('H:i') }}
                                                                ({{ bookingData.rowspan }}h)
                                                            </small>
                                                        {% endif %}
                                                    </td>
                                                {% endif %}
                                            {% else %}
                                                <td class="border-end nakkikone-schedule-cell"></td>
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="card shadow-sm border-0">
            <div class="card-header bg-dark text-white d-flex justify-content-between align-items-center" id="nakkikone-planner">
                <h2 class="h5 mb-0">{{ 'nakkikone.board.planner_title'|trans }}</h2>
            </div>
            <div class="card-body">
                {% if this.error %}
                    <div class="alert alert-warning" role="alert">{{ this.error }}</div>
                {% endif %}
                {% if this.message %}
                    <div class="alert alert-success" role="status">{{ this.message }}</div>
                {% endif %}

                <twig:Nakki:Definition :event="event" />

                {% if this.selectedDefinition %}
                    {{ form_start(form, {
                        attr: {
                            class: 'row g-3 align-items-end',
                            'data-action': 'live#action:prevent',
                            'data-live-action-param': 'addColumn',
                            autocomplete: 'off',
                        },
                    }) }}
                        <div class="d-none">
                            {{ form_widget(form.definition) }}
                        </div>

                        <div class="col-12">
                            <div class="row g-3">
                                <div class="col-6">
                                    {{ form_row(form.responsible) }}
                                </div>
                                <div class="col-6">
                                    {{ form_row(form.mattermostChannel) }}
                                </div>
                                <div class="col-12 col-lg-8 text-lg-end">
                                    <button type="submit" class="btn btn-primary w-100">
                                        {{ this.isDefinitionInUse() ? 'nakkikone.board.update_column'|trans : 'nakkikone.board.add_column'|trans }}
                                    </button>
                                </div>
                            </div>
                        </div>
                    {{ form_end(form, {render_rest: false}) }}
                {% endif %}
            </div>
        </div>

        <div class="row row-cols-1 row-cols-lg-2 row-cols-xxl-3 g-3 mt-3">
            {% for nakki in this.columns %}
                <div class="col">
                    <twig:Nakki:Column :nakkiId="nakki.id" key="{{ nakki.id }}" />
                </div>
            {% else %}
                <div class="col">
                    <div class="alert alert-info mb-0">{{ 'nakkikone.board.no_columns'|trans }}</div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>

symfony/templates/components/Nakki/NakkiCreateForm.html.twig
<div class="nakki-create-form">
    {% if notice %}
        <div class="alert alert-success">{{ notice }}</div>
    {% endif %}
    {% if error %}
        <div class="alert alert-warning">{{ error }}</div>
    {% endif %}

    <form class="row g-3" data-action="live#action:prevent" data-live-action-param="save">
        <div class="col-md-6">
        <label class="form-label fw-semibold">{{ 'nakkikone.board.definition_field'|trans }}</label>
            <select class="form-select"
                    data-model="definitionId"
                    required
                    {{ stimulus_controller('symfony/ux-autocomplete/autocomplete', {
                        tomSelectOptions: {
                            plugins: ['clear_button'],
                        },
                    }) }}>
                <option value="">{{ 'nakkikone.board.select_definition'|trans }}</option>
                {% for definition in this.getDefinitions() %}
                    <option value="{{ definition.id }}"
                            {% if definitionId == definition.id %}selected{% endif %}>
                        {{ definition.getName(app.request.locale) }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-3">
        <label class="form-label fw-semibold">{{ 'nakkikone.column.start_time'|trans }}</label>
            <input type="datetime-local" class="form-control" data-model="startAt" value="{{ startAt }}" required>
        </div>
        <div class="col-md-3">
        <label class="form-label fw-semibold">{{ 'nakkikone.column.end_time'|trans }}</label>
            <input type="datetime-local" class="form-control" data-model="endAt" value="{{ endAt }}" required>
        </div>
        <div class="col-md-3">
        <label class="form-label fw-semibold">{{ 'nakkikone.column.interval_hours'|trans }}</label>
            <input type="number" min="1" class="form-control" data-model="intervalHours" value="{{ intervalHours }}">
        </div>
        <div class="col-md-3">
        <label class="form-label fw-semibold">{{ 'nakkikone.column.responsible'|trans }}</label>
            <select class="form-select"
                    data-model="responsibleId"
                    {{ stimulus_controller('symfony/ux-autocomplete/autocomplete', {
                        tomSelectOptions: {
                            plugins: ['clear_button'],
                        },
                    }) }}>
                <option value="">{{ 'nakkikone.common.none'|trans }}</option>
                {% for member in this.getMembers() %}
                    <option value="{{ member.id }}"
                            {% if responsibleId == member.id %}selected{% endif %}>
                        {{ member.name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-6">
        <label class="form-label fw-semibold">{{ 'nakkikone.column.mattermost'|trans }}</label>
            <input type="text" class="form-control" data-model="mattermostChannel" value="{{ mattermostChannel }}">
        </div>
        <div class="col-12 text-end">
        <button type="submit" class="btn btn-primary">{{ 'nakkikone.column.create'|trans }}</button>
        </div>
    </form>
</div>